window.GAMES = [
  {
    id: "ratio-mix",
    title: "調飲達人",
    subtitle: "比與比值",
    description: "調出正確比例的飲料，在實作中掌握比與比值。",
    category: "數學",
    icon: "🥤",
    tone: "mint",
    url: "./ratio-mix-lanki/index.html",
    repo: "lankigame",
    tags: ["六年級", "比例", "比值", "實作"]
  },
  {
    id: "fraction-cowboy",
    title: "分數牛仔",
    subtitle: "射氣球對決",
    description: "兩人輪流判斷分數，瞄準氣球展開刺激對決。",
    category: "數學",
    icon: "🎈",
    tone: "coral",
    url: "https://lanki20.github.io/fraction/%E5%88%86%E6%95%B8%E7%89%9B%E4%BB%94%E5%B0%84%E6%B0%A3%E7%90%83%EF%BC%88%E5%85%A9%E4%BA%BA%E5%B0%8D%E6%88%B0%EF%BC%89index.html",
    repo: "fraction",
    tags: ["分數", "雙人", "挑戰"]
  },
  {
    id: "decimal",
    title: "小數點補位挑戰",
    subtitle: "小數練習",
    description: "觀察數位、正確補位，在挑戰中建立小數概念。",
    category: "數學",
    icon: "🔢",
    tone: "gold",
    url: "https://lanki20.github.io/Decimal/Decimal.html",
    repo: "Decimal",
    tags: ["小數", "數位", "補位"]
  },
  {
    id: "percentage",
    title: "百分率對對碰",
    subtitle: "百分率配對",
    description: "快速辨識百分率與對應數值，完成配對挑戰。",
    category: "數學",
    icon: "💯",
    tone: "lavender",
    url: "https://lanki20.github.io/percentage/percentage.html",
    repo: "percentage",
    tags: ["百分率", "配對", "數學"]
  },
  {
    id: "volume",
    title: "容積水位實驗",
    subtitle: "互動實驗",
    description: "觀察容器與水位變化，動手驗證容積關係。",
    category: "數學",
    icon: "🧪",
    tone: "mint",
    url: "https://lanki20.github.io/volume/volume.html",
    repo: "volume",
    tags: ["五年級", "容積", "水位", "實驗"]
  },
  {
    id: "cuboid",
    title: "長方體展開圖",
    subtitle: "剪邊與鉸鏈",
    description: "點選邊線模擬剪開，再把各面慢慢翻成展開圖。",
    category: "數學",
    icon: "📦",
    tone: "coral",
    url: "https://lanki20.github.io/cuboid/index%20(cuboid).html",
    repo: "cuboid",
    tags: ["長方體", "展開圖", "空間"]
  },
  {
    id: "cube",
    title: "正方體展開圖",
    subtitle: "動手剪剪看",
    description: "找出可剪開的邊，探索正方體不同的展開方式。",
    category: "數學",
    icon: "🧊",
    tone: "gold",
    url: "https://lanki20.github.io/cub/index(cub).html",
    repo: "cub",
    tags: ["正方體", "展開圖", "空間"]
  },
  {
    id: "shape-fold",
    title: "展開圖合體",
    subtitle: "慢動作摺疊",
    description: "從平面展開圖逐步摺成立體，理解面與面的關係。",
    category: "數學",
    icon: "🧩",
    tone: "lavender",
    url: "https://lanki20.github.io/shape/shape.html",
    repo: "shape",
    tags: ["正方體", "長方體", "展開圖", "摺疊"]
  },
  {
    id: "symmetry",
    title: "對稱軸摺疊實驗室",
    subtitle: "幾何探索",
    description: "試著沿不同軸線摺疊圖形，觀察是否能完全重合。",
    category: "數學",
    icon: "🦋",
    tone: "mint",
    url: "https://lanki20.github.io/symmetry/symmetry_lab.html",
    repo: "symmetry",
    tags: ["對稱", "對稱軸", "摺疊", "幾何"]
  },
  {
    id: "idiom-main",
    title: "成語填空大挑戰",
    subtitle: "語文闖關",
    description: "從線索找出正確成語，逐關累積你的語文力。",
    category: "語文",
    icon: "📚",
    tone: "gold",
    url: "https://lanki20.github.io/idiom/",
    repo: "idiom",
    tags: ["成語", "填空", "闖關"]
  },
  {
    id: "idiom-six",
    title: "36 則成語挖空闖關",
    subtitle: "六關挑戰",
    description: "完成六大關、36 則成語，把容易混淆的用法一次練熟。",
    category: "語文",
    icon: "🏮",
    tone: "coral",
    url: "https://lanki20.github.io/idiom2/",
    repo: "idiom2",
    tags: ["成語", "六關", "挖空", "練習"]
  },
  {
    id: "idiom-review",
    title: "成語運用複習測驗",
    subtitle: "填空大考驗",
    description: "把成語放進正確語境，檢查自己是否真的會運用。",
    category: "語文",
    icon: "✍️",
    tone: "lavender",
    url: "https://lanki20.github.io/idiom3/idiom3.html",
    repo: "idiom3",
    tags: ["成語", "運用", "複習", "測驗"]
  },
  {
    id: "words",
    title: "生字預習系統",
    subtitle: "課前暖身",
    description: "先認識課文生字，再帶著熟悉感進入新的學習內容。",
    category: "語文",
    icon: "📝",
    tone: "mint",
    url: "https://lanki20.github.io/words/words.html",
    repo: "words",
    tags: ["生字", "預習", "國語"]
  },
  {
    id: "grade-six-words",
    title: "六年級生字預習",
    subtitle: "自主學習工坊",
    description: "用互動任務預習六年級生字，依自己的步調建立字詞基礎。",
    category: "語文",
    icon: "🌱",
    tone: "coral",
    url: "https://lanki-learning-atelier.lanki-learning-atelier.workers.dev/",
    repo: "lanki-learning-atelier",
    tags: ["六年級", "生字", "預習", "自主學習"]
  },
  {
    id: "summer-reading",
    title: "暑假閱讀系統",
    subtitle: "六年級閱讀",
    description: "跟著閱讀任務前進，留下屬於自己的暑假閱讀足跡。",
    category: "語文",
    icon: "🌻",
    tone: "gold",
    url: "https://lanki20.github.io/summerreadingquiz/summerreadingquiz.html",
    repo: "summerreadingquiz",
    tags: ["六年級", "暑假", "閱讀", "任務"]
  },
  {
    id: "tea-game",
    title: "茶席用具擺設",
    subtitle: "互動遊戲",
    description: "辨識茶席用具並放到正確位置，完成自己的茶席。",
    category: "探索",
    icon: "🍵",
    tone: "mint",
    url: "https://lanki20.github.io/tea/teaindex.html",
    repo: "tea",
    tags: ["茶席", "用具", "擺設", "文化"]
  },
  {
    id: "tea-practicum",
    title: "埔小茶席實作解碼",
    subtitle: "步驟學習",
    description: "依序觀察茶席實作動作，把文化體驗拆成清楚步驟。",
    category: "探索",
    icon: "🫖",
    tone: "gold",
    url: "https://lanki20.github.io/Tea-Ceremony-Practicum/teaceremony.html",
    repo: "Tea-Ceremony-Practicum",
    tags: ["茶道", "茶席", "實作", "文化"]
  },
  {
    id: "deutsch",
    title: "旅遊德文自學幫手",
    subtitle: "情境語言",
    description: "從旅行情境學習實用德文，出發前先開口練習。",
    category: "探索",
    icon: "🗣️",
    tone: "lavender",
    url: "https://lanki20.github.io/Deutsch/Deutsch.html",
    repo: "Deutsch",
    tags: ["德文", "旅行", "自學", "語言"]
  },
  {
    id: "germany-travel",
    title: "德國旅行探索",
    subtitle: "行程學習",
    description: "用互動頁面整理德國旅行內容，邊規劃邊認識地方特色。",
    category: "探索",
    icon: "🚆",
    tone: "coral",
    url: "https://lanki20.github.io/germanytravel/germanytravel.html",
    repo: "germanytravel",
    tags: ["德國", "旅行", "行程", "探索"]
  },
  {
    id: "crc",
    title: "從新聞看見我的權利",
    subtitle: "兒童權利專欄",
    description: "從生活新聞出發，認識兒童權利和自己的日常連結。",
    category: "探索",
    icon: "📰",
    tone: "gold",
    url: "https://lanki20.github.io/CRC/CRC.html",
    repo: "CRC",
    tags: ["兒童權利", "新聞", "生活", "公民"]
  },
  {
    id: "quiz-battle",
    title: "問答火力戰",
    subtitle: "快問快答",
    description: "用題目展開節奏明快的問答對戰，適合課堂暖身與複習。",
    category: "語文",
    icon: "🚀",
    tone: "coral",
    url: "https://lanki20.github.io/1-6/quiz-battle/index.html",
    repo: "1-6",
    tags: ["問答", "對戰", "課堂", "複習"]
  },
  {
    id: "grouping",
    title: "504 抽籤分組系統",
    subtitle: "班級小工具",
    description: "快速完成抽籤與分組，把課堂時間留給真正的合作。",
    category: "教室",
    icon: "🎯",
    tone: "mint",
    url: "https://lanki20.github.io/grouping/",
    repo: "grouping",
    tags: ["504", "抽籤", "分組", "班級"]
  },
  {
    id: "assessment",
    title: "113 年篩選測驗",
    subtitle: "五年級評量",
    description: "用互動介面完成基本學習內容標準化評量練習。",
    category: "教室",
    icon: "✅",
    tone: "lavender",
    url: "https://lanki20.github.io/113basedtestingM/113basedtesting.html",
    repo: "113basedtestingM",
    tags: ["五年級", "評量", "篩選測驗", "練習"]
  }
];

